language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc pm2 -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "A46c883ZDdt++pmNU837AIkx4D4xwRIGWxvkwq4goyuJbxpbdZEDGwOvJRQ07OROz9czGbUKJUiSLMMy+YoibP+L/z4TkZvYgKR3BYl7oaJmQ2Ko6luG+QEfJICEYPQK/znc4oJsRsGWN64tsUYkEHIXx/zX743b/pspUhn5IktctYfcyPDTvvJuzz8HguMAaKpOPVU8iiUTatzF8vA/cO4XB34qnn8+5tV0UYwGGSOlnicfp8LakmILEggM3sIQ1qZre1wJ1ulqDEprvCk9ZwmM+DgC0ZO/N/EPrU3mkjTEZkBSupOJdANdVDSDg7q+XYLka3sQ9InPNws8srHOhvveNyj+Fh9zb1PQIGbVPJ65ktZQwgcEo8fYLTqmLTi0lY2nvud2dgOVPpQukiOxzsxBeCWNcz00PHZowhz1T3tcalUPrIUHdd0jFG7DG6bMlmJ7KuL9pskhfsfcCj7j04ukTEaH5SDxJbaESv8vfE2/TcQiLr6CyBL+1W2efHoS7yI8UpFokdjcQqbZvf361k4BGYK61Qpy5jft9w99uJUkXvcxNZq6zi5bxOGYxRx+tYw8ETr2fXh6OyuTSTBES4AoYHj6Ou1UdN9WD3dSs26Kx+wS/vLehQMHH09EykW/YqvGAwt/KVM5KiiaNIiFjntY3cUsovahBbmh349GmFg="
